### ISSUE TITLE
Data in the given link has been converted into word ids.

### ISSUE THREAD

**Issue by yhcc** [Yifan-Song793/NYT-for-joint-entity-and-relation-extraction#1]
Thanks for providing this pre-processing script, which i think is super useful for this field. 
I downloaded the data in the google drive, but found no raw_train.json contained in that link, only train.json/test.json/valid.json, and in them there are some nested lists. Would you like to take some time to check that, thx~

**Comment by yhcc** [comment]
And i found this [link](https://drive.google.com/file/d/1kAVwR051gjfKn3p6oKc7CzNT9g2Cjy6N/view) from [CopyRE](https://github.com/xiangrongzeng/copy_re])  seems to contain raw_tran.json file. But when i put these files in to nyt folder and run the code, the following exception occurred,
```cmd
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 56195/56195 [00:02<00:00, 20103.57it/s]
  0%|                                                                                                                                          | 0/4999 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "data_align.py", line 120, in <module>
    aligned = data_align.align(raw)
  File "data_align.py", line 92, in align
    raw_triplets = self.raw_train_sent2triplet[tmp]
KeyError: 'InQueens,NorthShoreTowers,neartheNassauborder,supplantedagolfcourse,andhousingreplacedagravelquarryinDouglaston.'
```
